rosbag2_bagfile_information:
  version: 5
  storage_identifier: sqlite3
  duration:
    nanoseconds: 40411334417
  starting_time:
    nanoseconds_since_epoch: 1761438606780462239
  message_count: 10069
  topics_with_message_count:
    - topic_metadata:
        name: /biped/joint_states
        type: sensor_msgs/msg/JointState
        serialization_format: cdr
        offered_qos_profiles: "- history: 1\n  depth: 1\n  reliability: 1\n  durability: 2\n  deadline:\n    sec: 9223372036\n    nsec: 854775807\n  lifespan:\n    sec: 9223372036\n    nsec: 854775807\n  liveliness: 1\n  liveliness_lease_duration:\n    sec: 9223372036\n    nsec: 854775807\n  avoid_ros_namespace_conventions: false"
      message_count: 10069
  compression_format: ""
  compression_mode: ""
  relative_file_paths:
    - s1_step_test_0.db3
  files:
    - path: s1_step_test_0.db3
      starting_time:
        nanoseconds_since_epoch: 1761438606780462239
      duration:
        nanoseconds: 40411334417
      message_count: 10069